# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

from ._operations import Operations
from ._asset_endpoint_profiles_operations import AssetEndpointProfilesOperations
from ._assets_operations import AssetsOperations
from ._billing_containers_operations import BillingContainersOperations
from ._operation_status_operations import OperationStatusOperations
from ._namespaces_operations import NamespacesOperations
from ._schema_registries_operations import SchemaRegistriesOperations
from ._namespace_assets_operations import NamespaceAssetsOperations
from ._credentials_operations import CredentialsOperations
from ._policies_operations import PoliciesOperations
from ._namespace_devices_operations import NamespaceDevicesOperations
from ._namespace_discovered_assets_operations import NamespaceDiscoveredAssetsOperations
from ._namespace_discovered_devices_operations import NamespaceDiscoveredDevicesOperations
from ._schemas_operations import SchemasOperations
from ._schema_versions_operations import SchemaVersionsOperations

from ._patch import __all__ as _patch_all
from ._patch import *  # type: ignore # pylint: disable=unused-wildcard-import
from ._patch import patch_sdk as _patch_sdk
__all__ = [
    'Operations',
    'AssetEndpointProfilesOperations',
    'AssetsOperations',
    'BillingContainersOperations',
    'OperationStatusOperations',
    'NamespacesOperations',
    'SchemaRegistriesOperations',
    'NamespaceAssetsOperations',
    'CredentialsOperations',
    'PoliciesOperations',
    'NamespaceDevicesOperations',
    'NamespaceDiscoveredAssetsOperations',
    'NamespaceDiscoveredDevicesOperations',
    'SchemasOperations',
    'SchemaVersionsOperations',
]
__all__.extend([p for p in _patch_all if p not in __all__])
_patch_sdk()