# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

from ._models_py3 import ActivateBringYourOwnRootRequest
from ._models_py3 import Asset
from ._models_py3 import AssetEndpointProfile
from ._models_py3 import AssetEndpointProfileListResult
from ._models_py3 import AssetEndpointProfileStatus
from ._models_py3 import AssetEndpointProfileStatusError
from ._models_py3 import AssetEndpointProfileUpdate
from ._models_py3 import AssetListResult
from ._models_py3 import AssetStatus
from ._models_py3 import AssetStatusDataset
from ._models_py3 import AssetStatusError
from ._models_py3 import AssetStatusEvent
from ._models_py3 import AssetUpdate
from ._models_py3 import Authentication
from ._models_py3 import AuthenticationUpdate
from ._models_py3 import BillingContainer
from ._models_py3 import BillingContainerListResult
from ._models_py3 import BringYourOwnRoot
from ._models_py3 import BrokerStateStoreDestinationConfiguration
from ._models_py3 import CertificateAuthorityConfiguration
from ._models_py3 import CertificateAuthorityConfigurationUpdate
from ._models_py3 import CertificateConfiguration
from ._models_py3 import CertificateConfigurationUpdate
from ._models_py3 import Credential
from ._models_py3 import CredentialListResult
from ._models_py3 import CredentialUpdate
from ._models_py3 import DataPoint
from ._models_py3 import DataPointBase
from ._models_py3 import Dataset
from ._models_py3 import DatasetBrokerStateStoreDestination
from ._models_py3 import DatasetDestination
from ._models_py3 import DatasetMqttDestination
from ._models_py3 import DatasetStorageDestination
from ._models_py3 import DeviceCredentialPolicy
from ._models_py3 import DeviceCredentialsRevokeRequest
from ._models_py3 import DeviceCredentialsRevokeResponse
from ._models_py3 import DeviceMessagingEndpoint
from ._models_py3 import DeviceMessagingEndpointUpdate
from ._models_py3 import DeviceRef
from ._models_py3 import DeviceRefUpdate
from ._models_py3 import DeviceStatus
from ._models_py3 import DeviceStatusEndpoint
from ._models_py3 import DeviceStatusEndpoints
from ._models_py3 import DiscoveredInboundEndpoints
from ._models_py3 import DiscoveredInboundEndpointsUpdate
from ._models_py3 import DiscoveredMessagingEndpoints
from ._models_py3 import DiscoveredMessagingEndpointsUpdate
from ._models_py3 import DiscoveredOutboundEndpoints
from ._models_py3 import DiscoveredOutboundEndpointsUpdate
from ._models_py3 import Error
from ._models_py3 import ErrorAdditionalInfo
from ._models_py3 import ErrorDetail
from ._models_py3 import ErrorDetails
from ._models_py3 import ErrorResponse
from ._models_py3 import Event
from ._models_py3 import EventBase
from ._models_py3 import EventDestination
from ._models_py3 import EventMqttDestination
from ._models_py3 import EventStorageDestination
from ._models_py3 import ExtendedLocation
from ._models_py3 import HostAuthentication
from ._models_py3 import HostAuthenticationUpdate
from ._models_py3 import InboundEndpoints
from ._models_py3 import InboundEndpointsUpdate
from ._models_py3 import LeafCertificateConfiguration
from ._models_py3 import LeafCertificateConfigurationUpdate
from ._models_py3 import ManagementAction
from ._models_py3 import ManagementGroup
from ._models_py3 import MessageSchemaReference
from ._models_py3 import Messaging
from ._models_py3 import MessagingEndpoint
from ._models_py3 import MessagingEndpoints
from ._models_py3 import MessagingEndpointsUpdate
from ._models_py3 import MigrateResult
from ._models_py3 import MqttDestinationConfiguration
from ._models_py3 import Namespace
from ._models_py3 import NamespaceAsset
from ._models_py3 import NamespaceAssetListResult
from ._models_py3 import NamespaceAssetStatus
from ._models_py3 import NamespaceAssetStatusDataset
from ._models_py3 import NamespaceAssetStatusEvent
from ._models_py3 import NamespaceAssetStatusEventGroup
from ._models_py3 import NamespaceAssetStatusManagementAction
from ._models_py3 import NamespaceAssetStatusManagementGroup
from ._models_py3 import NamespaceAssetStatusStream
from ._models_py3 import NamespaceAssetUpdate
from ._models_py3 import NamespaceDataset
from ._models_py3 import NamespaceDatasetDataPoint
from ._models_py3 import NamespaceDevice
from ._models_py3 import NamespaceDeviceListResult
from ._models_py3 import NamespaceDeviceUpdate
from ._models_py3 import NamespaceDiscoveredAsset
from ._models_py3 import NamespaceDiscoveredAssetListResult
from ._models_py3 import NamespaceDiscoveredAssetUpdate
from ._models_py3 import NamespaceDiscoveredDataset
from ._models_py3 import NamespaceDiscoveredDatasetDataPoint
from ._models_py3 import NamespaceDiscoveredDevice
from ._models_py3 import NamespaceDiscoveredDeviceListResult
from ._models_py3 import NamespaceDiscoveredDeviceUpdate
from ._models_py3 import NamespaceDiscoveredEvent
from ._models_py3 import NamespaceDiscoveredEventGroup
from ._models_py3 import NamespaceDiscoveredManagementAction
from ._models_py3 import NamespaceDiscoveredManagementGroup
from ._models_py3 import NamespaceDiscoveredStream
from ._models_py3 import NamespaceEvent
from ._models_py3 import NamespaceEventGroup
from ._models_py3 import NamespaceListResult
from ._models_py3 import NamespaceMessageSchemaReference
from ._models_py3 import NamespaceMigrateRequest
from ._models_py3 import NamespaceMigrateResponse
from ._models_py3 import NamespaceStream
from ._models_py3 import NamespaceUpdate
from ._models_py3 import Operation
from ._models_py3 import OperationDisplay
from ._models_py3 import OperationListResult
from ._models_py3 import OperationStatusResult
from ._models_py3 import OutboundEndpoints
from ._models_py3 import OutboundEndpointsUpdate
from ._models_py3 import Policy
from ._models_py3 import PolicyListResult
from ._models_py3 import PolicyUpdate
from ._models_py3 import ProxyResource
from ._models_py3 import Resource
from ._models_py3 import Schema
from ._models_py3 import SchemaListResult
from ._models_py3 import SchemaRegistry
from ._models_py3 import SchemaRegistryListResult
from ._models_py3 import SchemaRegistryUpdate
from ._models_py3 import SchemaVersion
from ._models_py3 import SchemaVersionListResult
from ._models_py3 import StatusConfig
from ._models_py3 import StatusError
from ._models_py3 import StorageDestinationConfiguration
from ._models_py3 import StreamDestination
from ._models_py3 import StreamMqttDestination
from ._models_py3 import StreamStorageDestination
from ._models_py3 import SystemAssignedServiceIdentity
from ._models_py3 import SystemData
from ._models_py3 import Topic
from ._models_py3 import TopicUpdate
from ._models_py3 import TrackedResource
from ._models_py3 import TrustSettings
from ._models_py3 import UsernamePasswordCredentials
from ._models_py3 import UsernamePasswordCredentialsUpdate
from ._models_py3 import X509CertificateCredentials
from ._models_py3 import X509CertificateCredentialsUpdate
from ._models_py3 import X509Credentials
from ._models_py3 import X509CredentialsUpdate


from ._microsoft_device_registry_management_service_enums import ActionType
from ._microsoft_device_registry_management_service_enums import AuthenticationMethod
from ._microsoft_device_registry_management_service_enums import BringYourOwnRootStatus
from ._microsoft_device_registry_management_service_enums import CreatedByType
from ._microsoft_device_registry_management_service_enums import DataPointObservabilityMode
from ._microsoft_device_registry_management_service_enums import DatasetDestinationTarget
from ._microsoft_device_registry_management_service_enums import EventDestinationTarget
from ._microsoft_device_registry_management_service_enums import EventObservabilityMode
from ._microsoft_device_registry_management_service_enums import Format
from ._microsoft_device_registry_management_service_enums import ManagementActionType
from ._microsoft_device_registry_management_service_enums import MigrateResultType
from ._microsoft_device_registry_management_service_enums import MqttDestinationQos
from ._microsoft_device_registry_management_service_enums import NamespaceDiscoveredManagementActionType
from ._microsoft_device_registry_management_service_enums import Origin
from ._microsoft_device_registry_management_service_enums import ProvisioningState
from ._microsoft_device_registry_management_service_enums import SchemaType
from ._microsoft_device_registry_management_service_enums import Scope
from ._microsoft_device_registry_management_service_enums import StreamDestinationTarget
from ._microsoft_device_registry_management_service_enums import SupportedKeyType
from ._microsoft_device_registry_management_service_enums import SystemAssignedServiceIdentityType
from ._microsoft_device_registry_management_service_enums import TopicRetainType
from ._patch import __all__ as _patch_all
from ._patch import *  # type: ignore # pylint: disable=unused-wildcard-import
from ._patch import patch_sdk as _patch_sdk
__all__ = [
    'ActivateBringYourOwnRootRequest',
    'Asset',
    'AssetEndpointProfile',
    'AssetEndpointProfileListResult',
    'AssetEndpointProfileStatus',
    'AssetEndpointProfileStatusError',
    'AssetEndpointProfileUpdate',
    'AssetListResult',
    'AssetStatus',
    'AssetStatusDataset',
    'AssetStatusError',
    'AssetStatusEvent',
    'AssetUpdate',
    'Authentication',
    'AuthenticationUpdate',
    'BillingContainer',
    'BillingContainerListResult',
    'BringYourOwnRoot',
    'BrokerStateStoreDestinationConfiguration',
    'CertificateAuthorityConfiguration',
    'CertificateAuthorityConfigurationUpdate',
    'CertificateConfiguration',
    'CertificateConfigurationUpdate',
    'Credential',
    'CredentialListResult',
    'CredentialUpdate',
    'DataPoint',
    'DataPointBase',
    'Dataset',
    'DatasetBrokerStateStoreDestination',
    'DatasetDestination',
    'DatasetMqttDestination',
    'DatasetStorageDestination',
    'DeviceCredentialPolicy',
    'DeviceCredentialsRevokeRequest',
    'DeviceCredentialsRevokeResponse',
    'DeviceMessagingEndpoint',
    'DeviceMessagingEndpointUpdate',
    'DeviceRef',
    'DeviceRefUpdate',
    'DeviceStatus',
    'DeviceStatusEndpoint',
    'DeviceStatusEndpoints',
    'DiscoveredInboundEndpoints',
    'DiscoveredInboundEndpointsUpdate',
    'DiscoveredMessagingEndpoints',
    'DiscoveredMessagingEndpointsUpdate',
    'DiscoveredOutboundEndpoints',
    'DiscoveredOutboundEndpointsUpdate',
    'Error',
    'ErrorAdditionalInfo',
    'ErrorDetail',
    'ErrorDetails',
    'ErrorResponse',
    'Event',
    'EventBase',
    'EventDestination',
    'EventMqttDestination',
    'EventStorageDestination',
    'ExtendedLocation',
    'HostAuthentication',
    'HostAuthenticationUpdate',
    'InboundEndpoints',
    'InboundEndpointsUpdate',
    'LeafCertificateConfiguration',
    'LeafCertificateConfigurationUpdate',
    'ManagementAction',
    'ManagementGroup',
    'MessageSchemaReference',
    'Messaging',
    'MessagingEndpoint',
    'MessagingEndpoints',
    'MessagingEndpointsUpdate',
    'MigrateResult',
    'MqttDestinationConfiguration',
    'Namespace',
    'NamespaceAsset',
    'NamespaceAssetListResult',
    'NamespaceAssetStatus',
    'NamespaceAssetStatusDataset',
    'NamespaceAssetStatusEvent',
    'NamespaceAssetStatusEventGroup',
    'NamespaceAssetStatusManagementAction',
    'NamespaceAssetStatusManagementGroup',
    'NamespaceAssetStatusStream',
    'NamespaceAssetUpdate',
    'NamespaceDataset',
    'NamespaceDatasetDataPoint',
    'NamespaceDevice',
    'NamespaceDeviceListResult',
    'NamespaceDeviceUpdate',
    'NamespaceDiscoveredAsset',
    'NamespaceDiscoveredAssetListResult',
    'NamespaceDiscoveredAssetUpdate',
    'NamespaceDiscoveredDataset',
    'NamespaceDiscoveredDatasetDataPoint',
    'NamespaceDiscoveredDevice',
    'NamespaceDiscoveredDeviceListResult',
    'NamespaceDiscoveredDeviceUpdate',
    'NamespaceDiscoveredEvent',
    'NamespaceDiscoveredEventGroup',
    'NamespaceDiscoveredManagementAction',
    'NamespaceDiscoveredManagementGroup',
    'NamespaceDiscoveredStream',
    'NamespaceEvent',
    'NamespaceEventGroup',
    'NamespaceListResult',
    'NamespaceMessageSchemaReference',
    'NamespaceMigrateRequest',
    'NamespaceMigrateResponse',
    'NamespaceStream',
    'NamespaceUpdate',
    'Operation',
    'OperationDisplay',
    'OperationListResult',
    'OperationStatusResult',
    'OutboundEndpoints',
    'OutboundEndpointsUpdate',
    'Policy',
    'PolicyListResult',
    'PolicyUpdate',
    'ProxyResource',
    'Resource',
    'Schema',
    'SchemaListResult',
    'SchemaRegistry',
    'SchemaRegistryListResult',
    'SchemaRegistryUpdate',
    'SchemaVersion',
    'SchemaVersionListResult',
    'StatusConfig',
    'StatusError',
    'StorageDestinationConfiguration',
    'StreamDestination',
    'StreamMqttDestination',
    'StreamStorageDestination',
    'SystemAssignedServiceIdentity',
    'SystemData',
    'Topic',
    'TopicUpdate',
    'TrackedResource',
    'TrustSettings',
    'UsernamePasswordCredentials',
    'UsernamePasswordCredentialsUpdate',
    'X509CertificateCredentials',
    'X509CertificateCredentialsUpdate',
    'X509Credentials',
    'X509CredentialsUpdate',
    'ActionType',
    'AuthenticationMethod',
    'BringYourOwnRootStatus',
    'CreatedByType',
    'DataPointObservabilityMode',
    'DatasetDestinationTarget',
    'EventDestinationTarget',
    'EventObservabilityMode',
    'Format',
    'ManagementActionType',
    'MigrateResultType',
    'MqttDestinationQos',
    'NamespaceDiscoveredManagementActionType',
    'Origin',
    'ProvisioningState',
    'SchemaType',
    'Scope',
    'StreamDestinationTarget',
    'SupportedKeyType',
    'SystemAssignedServiceIdentityType',
    'TopicRetainType',
]
__all__.extend([p for p in _patch_all if p not in __all__])
_patch_sdk()