# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

from enum import Enum
from azure.core import CaseInsensitiveEnumMeta


class ActionType(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Enum. Indicates the action type. "Internal" refers to actions that are for internal only APIs.
    """

    INTERNAL = "Internal"

class AuthenticationMethod(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Defines the method to authenticate the user of the client at the server.
    """

    #: The user authentication method is anonymous.
    ANONYMOUS = "Anonymous"
    #: The user authentication method is an x509 certificate.
    CERTIFICATE = "Certificate"
    #: The user authentication method is a username and password.
    USERNAME_PASSWORD = "UsernamePassword"

class BringYourOwnRootStatus(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Status of the Bring Your Own Root configuration.
    """

    #: The CSR has been generated and is waiting for the customer to provide the signed certificate.
    PENDING_ACTIVATION = "PendingActivation"
    #: The signed certificate has been successfully uploaded and validated, and the CA is active.
    ACTIVE = "Active"
    #: The certificate is nearing expiration (within renewal window) or has expired. A new CSR has
    #: been generated and is waiting for the customer to provide a new signed certificate.
    ACTIVE_BUT_PENDING_RENEWAL = "ActiveButPendingRenewal"

class CreatedByType(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """The type of identity that created the resource.
    """

    USER = "User"
    APPLICATION = "Application"
    MANAGED_IDENTITY = "ManagedIdentity"
    KEY = "Key"

class DataPointObservabilityMode(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """An indication of how the data point should be mapped to OpenTelemetry.
    """

    #: No mapping to OpenTelemetry.
    NONE = "None"
    #: Map as counter to OpenTelemetry.
    COUNTER = "Counter"
    #: Map as gauge to OpenTelemetry.
    GAUGE = "Gauge"
    #: Map as histogram to OpenTelemetry.
    HISTOGRAM = "Histogram"
    #: Map as log to OpenTelemetry.
    LOG = "Log"

class DatasetDestinationTarget(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """The set of supported dataset destinations for an asset.
    """

    #: MQTT target.
    MQTT = "Mqtt"
    #: Broker State Store target.
    BROKER_STATE_STORE = "BrokerStateStore"
    #: Storage target.
    STORAGE = "Storage"

class EventDestinationTarget(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """The set of supported event destinations for an asset.
    """

    #: MQTT target.
    MQTT = "Mqtt"
    #: Storage target.
    STORAGE = "Storage"

class EventObservabilityMode(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """An indication of how the event should be mapped to OpenTelemetry.
    """

    #: No mapping to OpenTelemetry.
    NONE = "None"
    #: Map as log to OpenTelemetry.
    LOG = "Log"

class Format(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Defines the schema format.
    """

    #: JSON Schema version draft 7 format
    JSON_SCHEMA_DRAFT7 = "JsonSchema/draft-07"
    #: Delta format
    DELTA1_0 = "Delta/1.0"

class ManagementActionType(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """The type of the action.
    """

    #: Call action type.
    CALL = "Call"
    #: Read action type.
    READ = "Read"
    #: Write action type.
    WRITE = "Write"

class MigrateResultType(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Result Type of Migrate Operation.
    """

    #: Resource Migrate operation is successful.
    SUCCEEDED = "Succeeded"
    #: Resource Migrate operation is not successful.
    FAILED = "Failed"

class MqttDestinationQos(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """The MQTT QoS setting. Defaults to QoS 1.
    """

    #: QoS 0.
    QOS0 = "Qos0"
    #: QoS 1.
    QOS1 = "Qos1"

class NamespaceDiscoveredManagementActionType(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """The type of the action.
    """

    #: Call action type.
    CALL = "Call"
    #: Read action type.
    READ = "Read"
    #: Write action type.
    WRITE = "Write"

class Origin(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """The intended executor of the operation; as in Resource Based Access Control (RBAC) and audit
    logs UX. Default value is "user,system".
    """

    USER = "user"
    SYSTEM = "system"
    USER_SYSTEM = "user,system"

class ProvisioningState(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """The provisioning status of the resource.
    """

    #: Resource has been created.
    SUCCEEDED = "Succeeded"
    #: Resource creation failed.
    FAILED = "Failed"
    #: Resource creation was canceled.
    CANCELED = "Canceled"
    #: Resource has been accepted by the server.
    ACCEPTED = "Accepted"
    #: Resource is deleting.
    DELETING = "Deleting"

class SchemaType(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Defines the schema type.
    """

    #: Message Schema schema type
    MESSAGE_SCHEMA = "MessageSchema"

class Scope(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Scope of the migrate resources operation.
    """

    #: Scoping the migration to resourceIds provided
    RESOURCES = "Resources"

class StreamDestinationTarget(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """The set of supported stream destinations for an asset.
    """

    #: MQTT target.
    MQTT = "Mqtt"
    #: Storage target.
    STORAGE = "Storage"

class SupportedKeyType(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Supported key types.
    """

    #: Indicates the ECC key type.
    ECC = "ECC"

class SystemAssignedServiceIdentityType(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Type of managed service identity (either system assigned, or none).
    """

    NONE = "None"
    SYSTEM_ASSIGNED = "SystemAssigned"

class TopicRetainType(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """When set to 'Keep', messages published to an MQTT broker will have the retain flag set.
    Default: 'Never'.
    """

    #: Retain the messages.
    KEEP = "Keep"
    #: Never retain messages.
    NEVER = "Never"
