# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

from copy import deepcopy
from typing import Any, Awaitable, TYPE_CHECKING

from azure.core.rest import AsyncHttpResponse, HttpRequest
from azure.mgmt.core import AsyncARMPipelineClient

from .. import models
from .._serialization import Deserializer, Serializer
from ._configuration import MicrosoftDeviceRegistryManagementServiceConfiguration
from .operations import AssetEndpointProfilesOperations, AssetsOperations, BillingContainersOperations, CredentialsOperations, NamespaceAssetsOperations, NamespaceDevicesOperations, NamespaceDiscoveredAssetsOperations, NamespaceDiscoveredDevicesOperations, NamespacesOperations, OperationStatusOperations, Operations, PoliciesOperations, SchemaRegistriesOperations, SchemaVersionsOperations, SchemasOperations

if TYPE_CHECKING:
    # pylint: disable=unused-import,ungrouped-imports
    from azure.core.credentials_async import AsyncTokenCredential

class MicrosoftDeviceRegistryManagementService:  # pylint: disable=client-accepts-api-version-keyword,too-many-instance-attributes
    """Microsoft.DeviceRegistry Resource Provider management API.

    :ivar operations: Operations operations
    :vartype operations: deviceregistry.mgmt.aio.operations.Operations
    :ivar asset_endpoint_profiles: AssetEndpointProfilesOperations operations
    :vartype asset_endpoint_profiles:
     deviceregistry.mgmt.aio.operations.AssetEndpointProfilesOperations
    :ivar assets: AssetsOperations operations
    :vartype assets: deviceregistry.mgmt.aio.operations.AssetsOperations
    :ivar billing_containers: BillingContainersOperations operations
    :vartype billing_containers: deviceregistry.mgmt.aio.operations.BillingContainersOperations
    :ivar operation_status: OperationStatusOperations operations
    :vartype operation_status: deviceregistry.mgmt.aio.operations.OperationStatusOperations
    :ivar namespaces: NamespacesOperations operations
    :vartype namespaces: deviceregistry.mgmt.aio.operations.NamespacesOperations
    :ivar schema_registries: SchemaRegistriesOperations operations
    :vartype schema_registries: deviceregistry.mgmt.aio.operations.SchemaRegistriesOperations
    :ivar namespace_assets: NamespaceAssetsOperations operations
    :vartype namespace_assets: deviceregistry.mgmt.aio.operations.NamespaceAssetsOperations
    :ivar credentials: CredentialsOperations operations
    :vartype credentials: deviceregistry.mgmt.aio.operations.CredentialsOperations
    :ivar policies: PoliciesOperations operations
    :vartype policies: deviceregistry.mgmt.aio.operations.PoliciesOperations
    :ivar namespace_devices: NamespaceDevicesOperations operations
    :vartype namespace_devices: deviceregistry.mgmt.aio.operations.NamespaceDevicesOperations
    :ivar namespace_discovered_assets: NamespaceDiscoveredAssetsOperations operations
    :vartype namespace_discovered_assets:
     deviceregistry.mgmt.aio.operations.NamespaceDiscoveredAssetsOperations
    :ivar namespace_discovered_devices: NamespaceDiscoveredDevicesOperations operations
    :vartype namespace_discovered_devices:
     deviceregistry.mgmt.aio.operations.NamespaceDiscoveredDevicesOperations
    :ivar schemas: SchemasOperations operations
    :vartype schemas: deviceregistry.mgmt.aio.operations.SchemasOperations
    :ivar schema_versions: SchemaVersionsOperations operations
    :vartype schema_versions: deviceregistry.mgmt.aio.operations.SchemaVersionsOperations
    :param credential: Credential needed for the client to connect to Azure. Required.
    :type credential: ~azure.core.credentials_async.AsyncTokenCredential
    :param subscription_id: The ID of the target subscription. The value must be an UUID. Required.
    :type subscription_id: str
    :param base_url: Service URL. Default value is "https://management.azure.com".
    :type base_url: str
    :keyword api_version: Api Version. Default value is "2026-03-01-preview". Note that overriding
     this default value may result in unsupported behavior.
    :paramtype api_version: str
    :keyword int polling_interval: Default waiting time between two polls for LRO operations if no
     Retry-After header is present.
    """

    def __init__(
        self,
        credential: "AsyncTokenCredential",
        subscription_id: str,
        base_url: str = "https://management.azure.com",
        **kwargs: Any
    ) -> None:
        self._config = MicrosoftDeviceRegistryManagementServiceConfiguration(credential=credential, subscription_id=subscription_id, **kwargs)
        self._client = AsyncARMPipelineClient(base_url=base_url, config=self._config, **kwargs)

        client_models = {k: v for k, v in models.__dict__.items() if isinstance(v, type)}
        self._serialize = Serializer(client_models)
        self._deserialize = Deserializer(client_models)
        self._serialize.client_side_validation = False
        self.operations = Operations(
            self._client, self._config, self._serialize, self._deserialize
        )
        self.asset_endpoint_profiles = AssetEndpointProfilesOperations(
            self._client, self._config, self._serialize, self._deserialize
        )
        self.assets = AssetsOperations(
            self._client, self._config, self._serialize, self._deserialize
        )
        self.billing_containers = BillingContainersOperations(
            self._client, self._config, self._serialize, self._deserialize
        )
        self.operation_status = OperationStatusOperations(
            self._client, self._config, self._serialize, self._deserialize
        )
        self.namespaces = NamespacesOperations(
            self._client, self._config, self._serialize, self._deserialize
        )
        self.schema_registries = SchemaRegistriesOperations(
            self._client, self._config, self._serialize, self._deserialize
        )
        self.namespace_assets = NamespaceAssetsOperations(
            self._client, self._config, self._serialize, self._deserialize
        )
        self.credentials = CredentialsOperations(
            self._client, self._config, self._serialize, self._deserialize
        )
        self.policies = PoliciesOperations(
            self._client, self._config, self._serialize, self._deserialize
        )
        self.namespace_devices = NamespaceDevicesOperations(
            self._client, self._config, self._serialize, self._deserialize
        )
        self.namespace_discovered_assets = NamespaceDiscoveredAssetsOperations(
            self._client, self._config, self._serialize, self._deserialize
        )
        self.namespace_discovered_devices = NamespaceDiscoveredDevicesOperations(
            self._client, self._config, self._serialize, self._deserialize
        )
        self.schemas = SchemasOperations(
            self._client, self._config, self._serialize, self._deserialize
        )
        self.schema_versions = SchemaVersionsOperations(
            self._client, self._config, self._serialize, self._deserialize
        )


    def _send_request(
        self,
        request: HttpRequest,
        **kwargs: Any
    ) -> Awaitable[AsyncHttpResponse]:
        """Runs the network request through the client's chained policies.

        >>> from azure.core.rest import HttpRequest
        >>> request = HttpRequest("GET", "https://www.example.org/")
        <HttpRequest [GET], url: 'https://www.example.org/'>
        >>> response = await client._send_request(request)
        <AsyncHttpResponse: 200 OK>

        For more information on this code flow, see https://aka.ms/azsdk/dpcodegen/python/send_request

        :param request: The network request you want to make. Required.
        :type request: ~azure.core.rest.HttpRequest
        :keyword bool stream: Whether the response payload will be streamed. Defaults to False.
        :return: The response of your network call. Does not do error handling on your response.
        :rtype: ~azure.core.rest.AsyncHttpResponse
        """

        request_copy = deepcopy(request)
        request_copy.url = self._client.format_url(request_copy.url)
        return self._client.send_request(request_copy, **kwargs)

    async def close(self) -> None:
        await self._client.close()

    async def __aenter__(self) -> "MicrosoftDeviceRegistryManagementService":
        await self._client.__aenter__()
        return self

    async def __aexit__(self, *exc_details) -> None:
        await self._client.__aexit__(*exc_details)
